# Generated by Django 4.1.2 on 2022-11-23 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_amountingredient_id_alter_favoriterecipe_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(help_text='Фото блюда', upload_to='recipes/photo/', verbose_name='Фото'),
        ),
    ]
