# Generated by Django 4.1.2 on 2022-12-14 12:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amountingredient',
            name='amount',
            field=models.PositiveSmallIntegerField(help_text='Введите количество ингредиента для рецепта', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.PositiveIntegerField(help_text='Введите еденицу измерения', max_length=120, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Еденица измерения'),
        ),
    ]
